"""Add password column to users

Revision ID: 61c448b59077
Revises: e9c26f652c70
Create Date: 2025-12-08 05:54:27.790091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61c448b59077'
down_revision: Union[str, Sequence[str], None] = 'e9c26f652c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('messages')
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('onboarding_thread_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['onboarding_thread_id'])
   # op.drop_column('users', 'updatedAt')
    op.alter_column('users', 'createdAt', new_column_name='created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at', new_column_name='createdAt')
    # 2. Drop the columns we added
    op.drop_constraint(None, 'users', type_='unique') # Drops the onboarding_thread_id unique constraint
    op.drop_column('users', 'onboarding_thread_id')
    op.drop_column('users', 'password')

    # ### end Alembic commands ###
